### ISSUE TITLE
 TypeError in HintRequests#index

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#44]
Showing /home/ondracka/kolecko/app/views/hint_requests/index.haml where line #30 raised:

"can't convert nil into Float"

the problematic line seems to be:

'%.1f' % sent_hints.average(:rating) || 3.0 

I did this by creating a hint request with one team, submitting a hint by other team and when I went to the page with "received hints" with the original team -> Booom.

**Comment by KoleckoOrg** [comment]
app/models/team.rb:36:in `%'
app/models/team.rb:36:in `hint_quality'
app/views/hint_requests/index.haml:30:in `block (2 levels) in _app_views_hint_requests_index_haml__1848451660319355758_70001638178480'
app/views/hint_requests/index.haml:28:in `block in _app_views_hint_requests_index_haml__1848451660319355758_70001638178480'
app/views/hint_requests/index.haml:10:in `_app_views_hint_requests_index_haml__1848451660319355758_70001638178480'

**Comment by KoleckoOrg** [comment]
`app/models/team.rb:36:in `%'
app/models/team.rb:36:in `hint_quality'
app/views/hint_requests/index.haml:30:in `block (2 levels) in _app_views_hint_requests_index_haml__1848451660319355758_70001638178480'
app/views/hint_requests/index.haml:28:in `block in _app_views_hint_requests_index_haml__1848451660319355758_70001638178480'
app/views/hint_requests/index.haml:10:in `_app_views_hint_requests_index_haml__1848451660319355758_70001638178480'`
